export const skills = [
	"Frontend",
	"Backend",
	"Mobile",
	"Fullstack",
	"JavaScript",
	"TypeScript",
	"React",
	"React Native",
	"Python",
	"Java",
	"C++",
	"C#",
	"PHP",
	"Ruby",
	"Go",
	"Swift",
	"Kotlin",
	"SQL",
	"MySQL",
	"MongoDB",
	"Firebase",
	"AWS",
	"Azure",
	"DevOps",
	"Machine Learning",
	"Data Science",
	"Cybersecurity",
	"UI/UX Design",
	"Agile",
	"Scrum",
	"SAP",
	"GraphQL",
	"Node.js",
	"Express.js",
	"Linux",
	"Elixir",
	"Bash",
];

export const firstnames = [
	"James",
	"Mary",
	"John",
	"Patricia",
	"Robert",
	"Jennifer",
	"Michael",
	"Linda",
	"William",
	"Elizabeth",
	"David",
	"Barbara",
	"Richard",
	"Susan",
	"Joseph",
	"Jessica",
	"Thomas",
	"Sarah",
	"Charles",
	"Karen",
	"Christopher",
	"Nancy",
	"Daniel",
	"Lisa",
	"Matthew",
	"Betty",
	"Anthony",
	"Margaret",
	"Mark",
	"Sandra",
	"Donald",
	"Ashley",
	"Steven",
	"Kimberly",
	"Paul",
	"Emily",
	"Andrew",
	"Donna",
	"Joshua",
	"Michelle",
	"Kenneth",
	"Dorothy",
	"Kevin",
	"Carol",
	"Brian",
	"Amanda",
	"George",
	"Melissa",
	"Edward",
	"Deborah",
	"Ronald",
	"Stephanie",
	"Timothy",
	"Rebecca",
	"Jason",
	"Laura",
	"Jeffrey",
	"Sharon",
	"Ryan",
	"Cynthia",
	"Jacob",
	"Kathleen",
	"Gary",
	"Amy",
	"Nicholas",
	"Shirley",
	"Eric",
	"Angela",
	"Stephen",
	"Helen",
	"Jonathan",
	"Anna",
	"Larry",
	"Brenda",
	"Justin",
	"Pamela",
	"Scott",
	"Nicole",
	"Brandon",
	"Emma",
	"Frank",
	"Samantha",
	"Benjamin",
	"Katherine",
	"Gregory",
	"Christine",
	"Raymond",
	"Debra",
	"Samuel",
	"Rachel",
	"Patrick",
	"Catherine",
	"Alexander",
	"Carolyn",
	"Jack",
	"Janet",
	"Dennis",
	"Ruth",
	"Jerry",
	"Maria",
	"Tyler",
	"Heather",
	"Aaron",
	"Diane",
	"Jose",
	"Virginia",
	"Henry",
	"Julie",
	"Douglas",
	"Joyce",
	"Adam",
	"Victoria",
	"Peter",
	"Olivia",
	"Nathan",
	"Kelly",
	"Zachary",
	"Christina",
	"Walter",
	"Lauren",
	"Kyle",
	"Joan",
	"Harold",
	"Evelyn",
	"Carl",
	"Judith",
	"Jeremy",
	"Megan",
	"Keith",
	"Cheryl",
	"Roger",
	"Andrea",
	"Gerald",
	"Hannah",
	"Ethan",
	"Martha",
	"Arthur",
	"Jacqueline",
	"Terry",
	"Frances",
	"Christian",
	"Gloria",
	"Sean",
	"Ann",
	"Lawrence",
	"Teresa",
	"Austin",
	"Kathryn",
	"Joe",
	"Sara",
	"Noah",
	"Janice",
	"Jesse",
	"Jean",
	"Albert",
	"Alice",
	"Bryan",
	"Madison",
	"Billy",
	"Doris",
	"Bruce",
	"Abigail",
	"Willie",
	"Julia",
	"Jordan",
	"Judy",
	"Dylan",
	"Grace",
	"Alan",
	"Denise",
	"Ralph",
	"Amber",
	"Gabriel",
	"Marilyn",
	"Roy",
	"Beverly",
	"Juan",
	"Danielle",
	"Wayne",
	"Theresa",
	"Eugene",
	"Sophia",
	"Logan",
	"Marie",
	"Randy",
	"Diana",
	"Louis",
	"Brittany",
	"Russell",
	"Natalie",
	"Vincent",
	"Isabella",
	"Philip",
	"Charlotte",
	"Bobby",
	"Rose",
	"Johnny",
	"Alexis",
	"Bradley",
	"Kayla",
];

export const lastnames = [
	"Smith",
	"Johnson",
	"Williams",
	"Brown",
	"Jones",
	"Garcia",
	"Miller",
	"Davis",
	"Rodriguez",
	"Martinez",
	"Hernandez",
	"Lopez",
	"Gonzalez",
	"Wilson",
	"Anderson",
	"Thomas",
	"Taylor",
	"Moore",
	"Jackson",
	"Martin",
	"Lee",
	"Perez",
	"Thompson",
	"White",
	"Harris",
	"Sanchez",
	"Clark",
	"Ramirez",
	"Lewis",
	"Robinson",
	"Walker",
	"Young",
	"Allen",
	"King",
	"Wright",
	"Scott",
	"Torres",
	"Nguyen",
	"Hill",
	"Flores",
	"Green",
	"Adams",
	"Nelson",
	"Baker",
	"Hall",
	"Rivera",
	"Campbell",
	"Mitchell",
	"Carter",
	"Roberts",
	"Gomez",
	"Phillips",
	"Evans",
	"Turner",
	"Diaz",
	"Parker",
	"Cruz",
	"Edwards",
	"Collins",
	"Reyes",
	"Stewart",
	"Morris",
	"Morales",
	"Murphy",
	"Cook",
	"Rogers",
	"Gutierrez",
	"Ortiz",
	"Morgan",
	"Cooper",
	"Peterson",
	"Bailey",
	"Reed",
	"Kelly",
	"Howard",
	"Ramos",
	"Kim",
	"Cox",
	"Ward",
	"Richardson",
	"Watson",
	"Brooks",
	"Chavez",
	"Wood",
	"James",
	"Bennett",
	"Gray",
	"Mendoza",
	"Ruiz",
	"Hughes",
	"Price",
	"Alvarez",
	"Castillo",
	"Sanders",
	"Patel",
	"Myers",
	"Long",
	"Ross",
	"Foster",
	"Jimenez",
	"Powell",
	"Jenkins",
	"Perry",
	"Russell",
	"Sullivan",
	"Bell",
	"Coleman",
	"Butler",
	"Henderson",
	"Barnes",
	"Gonzales",
	"Fisher",
	"Vasquez",
	"Simmons",
	"Romero",
	"Jordan",
	"Patterson",
	"Alexander",
	"Hamilton",
	"Graham",
	"Reynolds",
	"Griffin",
	"Wallace",
	"Moreno",
	"West",
	"Cole",
	"Hayes",
	"Bryant",
	"Herrera",
	"Gibson",
	"Ellis",
	"Tran",
	"Medina",
	"Aguilar",
	"Stevens",
	"Murray",
	"Ford",
	"Castro",
	"Marshall",
	"Owens",
	"Harrison",
	"Fernandez",
	"McDonald",
	"Woods",
	"Washington",
	"Kennedy",
	"Wells",
	"Vargas",
	"Henry",
	"Chen",
	"Freeman",
	"Webb",
	"Tucker",
	"Guzman",
	"Burns",
	"Crawford",
	"Olson",
	"Simpson",
	"Porter",
	"Hunter",
	"Gordon",
	"Mendez",
	"Silva",
	"Shaw",
	"Snyder",
	"Mason",
	"Dixon",
	"Munoz",
	"Hunt",
	"Hicks",
	"Holmes",
	"Palmer",
	"Wagner",
	"Black",
	"Robertson",
	"Boyd",
	"Rose",
	"Stone",
	"Salazar",
	"Fox",
	"Warren",
	"Mills",
	"Meyer",
	"Rice",
	"Schmidt",
	"Garza",
	"Daniels",
	"Ferguson",
	"Nichols",
	"Stephens",
	"Soto",
	"Weaver",
	"Ryan",
	"Gardner",
	"Payne",
	"Grant",
	"Dunn",
	"Kelley",
	"Spencer",
	"Hawkins",
];

export const companies = [
	"Apple",
	"Microsoft",
	"Google",
	"Amazon",
	"Meta",
	"Samsung",
	"Intel",
	"IBM",
	"Oracle",
	"Nvidia",
	"Adobe",
	"Salesforce",
	"Cisco",
	"Tencent",
	"Alibaba",
	"TSMC",
	"Sony",
	"Qualcomm",
	"Dell",
	"HP",
	"Uber",
	"Lyft",
	"Airbnb",
	"Spotify",
	"Netflix",
	"Zoom",
	"Snap",
	"Pinterest",
	"PayPal",
	"Square",
	"Block",
	"Slack",
	"Atlassian",
	"Dropbox",
	"Shopify",
	"Stripe",
	"Palantir",
	"Red Hat",
	"ServiceNow",
	"Workday",
	"GitHub",
	"Bitbucket",
	"DigitalOcean",
	"Cloudflare",
	"Snowflake",
	"Datadog",
	"Twilio",
	"Okta",
	"MongoDB",
	"Splunk",
	"ZoomInfo",
	"Elastic",
	"Unity",
	"Roku",
	"DocuSign",
	"HubSpot",
	"Asana",
	"Notion",
	"Miro",
	"Figma",
	"Canva",
	"Bubble",
	"OutSystems",
	"Vercel",
	"Netlify",
	"Heroku",
	"JetBrains",
	"Postman",
	"MuleSoft",
	"Tableau",
	"Looker",
	"Alteryx",
	"UiPath",
	"Automation Anywhere",
	"Blue Prism",
	"Lucid",
	"Trello",
	"Basecamp",
	"ClickUp",
	"Monday.com",
	"Jira",
	"Confluence",
	"Zapier",
	"IFTTT",
	"Segment",
	"Amplitude",
	"Mixpanel",
	"Heap",
	"New Relic",
	"PagerDuty",
	"Sentry",
	"Databricks",
	"Cloudera",
	"Hortonworks",
	"Nutanix",
	"Rubrik",
	"Cohesity",
	"Snow Software",
	"Ivanti",
	"SolarWinds",
	"CrowdStrike",
	"SentinelOne",
	"Darktrace",
	"Fortinet",
	"Palo Alto Networks",
	"Check Point",
	"Sophos",
	"Trend Micro",
	"McAfee",
	"NortonLifeLock",
	"Box",
	"Egnyte",
	"Nextcloud",
	"Synology",
	"QNAP",
	"Seagate",
	"Western Digital",
	"Kingston",
	"Sandisk",
	"Corsair",
	"Logitech",
	"Razer",
	"SteelSeries",
	"Alienware",
	"MSI",
	"ASUS",
	"Acer",
	"Lenovo",
	"Gigabyte",
	"EVGA",
	"Zotac",
	"Anker",
	"Belkin",
	"TP-Link",
	"Netgear",
	"Ubiquiti",
	"Arista",
	"Juniper",
	"F5 Networks",
	"Citrix",
	"VMware",
	"Parallels",
	"Virtuozzo",
	"Canonical",
	"SUSE",
	"Debian",
	"Fedora",
	"Red Hat Enterprise",
	"CentOS",
	"Arch Linux",
	"OpenSUSE",
	"Android",
	"iOS",
	"Chrome OS",
	"HarmonyOS",
	"React",
	"Angular",
	"Vue",
	"Next.js",
	"Nuxt.js",
	"Svelte",
	"Ember.js",
	"Backbone.js",
	"Laravel",
	"Symfony",
	"Django",
	"Flask",
	"Rails",
	"Spring",
	"Express",
	"FastAPI",
	"NestJS",
	"Meteor",
	"Phoenix",
	"Elixir",
	"GoLang",
	"Rust",
	"TypeScript",
	"Python",
	"JavaScript",
	"Java",
	"C#",
	"C++",
	"Swift",
	"Kotlin",
	"Perl",
	"R",
	"MATLAB",
	"Julia",
	"Scala",
	"Haskell",
	"Clojure",
	"Elm",
	"OCaml",
	"Erlang",
	"Apache",
	"Nginx",
	"IIS",
	"Tomcat",
	"GlassFish",
];

export const jobposts = [
	{
		title: "Frontend Engineer",
		text: "We are looking for a talented Frontend Engineer to help build and maintain our web applications. You'll work closely with designers and backend developers to deliver seamless user experiences. Candidates should be proficient in JavaScript and have experience with modern frameworks.",
		jobSkills: ["Frontend", "JavaScript", "React", "UI/UX Design"],
		employer: "Google",
	},
	{
		title: "Fullstack Developer",
		text: "Join our agile team to build robust and scalable web applications. We're seeking a Fullstack Developer comfortable working on both the client and server sides. Experience with Node.js and React is a big plus.",
		jobSkills: ["Fullstack", "JavaScript", "Node.js", "React", "Agile"],
		employer: "Microsoft",
	},
	{
		title: "Mobile App Developer",
		text: "Our team is building the next generation of mobile applications. We're hiring a Mobile Developer with experience in either React Native or Swift. You'll contribute to creating performant, cross-platform apps.",
		jobSkills: ["Mobile", "React Native", "Swift"],
		employer: "Meta",
	},
	{
		title: "Backend Software Engineer",
		text: "As a Backend Software Engineer, you'll design and implement APIs and services that scale. Experience in Go and working with SQL or NoSQL databases is highly desired. Knowledge of cloud services is a bonus.",
		jobSkills: ["Backend", "Go", "SQL", "AWS"],
		employer: "Amazon",
	},
	{
		title: "DevOps Engineer",
		text: "We are seeking a DevOps Engineer to improve our infrastructure and deployment pipelines. You'll work with developers to automate processes and ensure reliability across environments.",
		jobSkills: ["DevOps", "Linux", "AWS", "Bash"],
		employer: "Netflix",
	},
	{
		title: "Data Scientist",
		text: "Looking for a Data Scientist to work with our analytics team and uncover insights from massive datasets. Proficiency in Python, SQL, and experience in Machine Learning is essential.",
		jobSkills: ["Data Science", "Python", "Machine Learning", "SQL"],
		employer: "IBM",
	},
	{
		title: "Cybersecurity Engineer",
		text: "We need a Cybersecurity Engineer to strengthen our defenses and safeguard our applications and infrastructure. Familiarity with threat modeling, secure coding practices, and audits is expected.",
		jobSkills: ["Cybersecurity", "Linux", "Python", "Bash"],
		employer: "Cisco",
	},
	{
		title: "React Developer",
		text: "We're hiring a React Developer to join our dynamic frontend team. You'll create responsive and interactive interfaces using modern JavaScript technologies in a fast-paced environment.",
		jobSkills: ["JavaScript", "React", "Frontend"],
		employer: "Spotify",
	},
	{
		title: "Machine Learning Engineer",
		text: "We are building intelligent solutions using AI. As a Machine Learning Engineer, you’ll develop and optimize algorithms to improve product experiences. Solid knowledge in Python, data structures, and ML frameworks is required.",
		jobSkills: ["Machine Learning", "Python", "Data Science", "AWS"],
		employer: "OpenAI",
	},
	{
		title: "Software Engineer (Node.js)",
		text: "Our backend team is growing, and we're looking for a Software Engineer with strong Node.js experience. You'll be building scalable services and RESTful APIs that power our core products.",
		jobSkills: ["Backend", "Node.js", "Express.js", "JavaScript"],
		employer: "Stripe",
	},
	{
		title: "Cloud Infrastructure Engineer",
		text: "We're seeking an experienced Cloud Infrastructure Engineer to manage and scale our cloud-based platforms. You'll ensure high availability and optimize our deployments across multiple environments.",
		jobSkills: ["AWS", "DevOps", "Linux"],
		employer: "Oracle",
	},
	{
		title: "Backend API Developer",
		text: "Join our backend team to develop scalable APIs powering millions of users. We're looking for someone skilled in Express.js and database integration, with a focus on performance and reliability.",
		jobSkills: ["Backend", "Node.js", "Express.js", "MongoDB", "SQL"],
		employer: "Shopify",
	},
	{
		title: "Junior Frontend Developer",
		text: "We are hiring a junior developer to support our frontend projects. Ideal candidates have a strong foundation in HTML, CSS, and JavaScript, with a willingness to learn modern frameworks.",
		jobSkills: ["JavaScript"],
		employer: "Canva",
	},
	{
		title: "AI/ML Research Engineer",
		text: "As an AI/ML Research Engineer, you'll work on cutting-edge models and contribute to applied machine learning projects. Candidates must have strong programming skills and a research-oriented mindset.",
		jobSkills: ["Machine Learning", "Python", "Data Science", "SQL"],
		employer: "Nvidia",
	},
	{
		title: "Cross-Platform Mobile Developer",
		text: "Help us bring our app to every user. We're looking for a cross-platform mobile developer with experience in both React Native and Firebase for real-time data integration.",
		jobSkills: ["Mobile", "React Native", "Firebase"],
		employer: "Dropbox",
	},
	{
		title: "Senior DevOps Architect",
		text: "We are building out our DevOps architecture and need a senior engineer to lead our automation, CI/CD, and infrastructure-as-code efforts. Deep experience in cloud platforms is required.",
		jobSkills: ["DevOps", "Azure", "Bash", "Linux", "Agile"],
		employer: "Red Hat",
	},
	{
		title: "Software Engineer - Game Tools",
		text: "Join our tools team to create developer-facing software that enhances our game engine pipeline. Experience with C++, scripting, and a passion for gaming is a must.",
		jobSkills: ["C++", "Python", "UI/UX Design"],
		employer: "Unity",
	},
	{
		title: "Web Developer",
		text: "We are hiring a Web Developer to build dynamic user interfaces and maintain existing web properties. Experience in JavaScript frameworks and content optimization is desired.",
		jobSkills: ["Frontend", "JavaScript", "React"],
		employer: "Airbnb",
	},
	{
		title: "Platform Engineer",
		text: "Be a key player in scaling our infrastructure and development tooling. We’re looking for a Platform Engineer who thrives in an agile environment and enjoys improving developer experience.",
		jobSkills: ["Go", "DevOps"],
		employer: "Atlassian",
	},
	{
		title: "UI/UX Engineer",
		text: "We need a UI/UX Engineer to help design and implement user-centric features. You'll collaborate closely with design and development teams to craft intuitive and visually stunning applications.",
		jobSkills: ["UI/UX Design", "TypeScript", "React", "GraphQL", "Agile"],
		employer: "Figma",
	},
	{
		title: "PHP Backend Developer",
		text: "We're looking for a skilled PHP Backend Developer to join our growing web platform team. You'll be maintaining legacy systems and contributing to modern service architecture.",
		jobSkills: ["PHP", "MySQL"],
		employer: "Meta",
	},
	{
		title: "Android Developer",
		text: "Join our mobile team to build performant and scalable Android applications. Proficiency in Kotlin and experience with cloud integration are required.",
		jobSkills: ["Mobile", "Kotlin", "Firebase", "Agile"],
		employer: "Samsung",
	},
	{
		title: "Junior Software Engineer",
		text: "As a Junior Software Engineer, you will assist senior developers in coding, testing, and debugging across various projects. A basic understanding of JavaScript and a drive to learn is essential.",
		jobSkills: ["JavaScript"],
		employer: "IBM",
	},
	{
		title: "C# Developer",
		text: "We are in need of a C# Developer to support our enterprise application suite. Experience with .NET, SQL, and team collaboration in Agile environments is highly valued.",
		jobSkills: ["C#", "SQL", "Agile"],
		employer: "Microsoft",
	},
	{
		title: "Data Platform Engineer",
		text: "Our data team is hiring a Platform Engineer to optimize large-scale data pipelines and storage systems. Strong SQL knowledge and cloud experience are required.",
		jobSkills: ["SQL", "AWS", "Python", "Data Science"],
		employer: "Amazon",
	},
	{
		title: "iOS Developer",
		text: "We’re seeking an iOS Developer to create elegant and robust mobile applications. You must have strong knowledge of Swift and experience with UI/UX best practices.",
		jobSkills: ["Mobile", "Swift", "UI/UX Design"],
		employer: "Spotify",
	},
	{
		title: "Fullstack Engineer - SaaS Platform",
		text: "Join our SaaS platform team as a Fullstack Engineer. You will work on scalable web applications using modern stacks and contribute across the front and backend.",
		jobSkills: ["Fullstack", "React", "Node.js", "MongoDB", "GraphQL"],
		employer: "Stripe",
	},
	{
		title: "Elixir Developer",
		text: "We are experimenting with Elixir to build fault-tolerant distributed systems. If you have experience with the Elixir ecosystem and functional programming, we’d love to talk.",
		jobSkills: ["Elixir", "Backend"],
		employer: "Discord",
	},
	{
		title: "Agile Software Developer",
		text: "We need a versatile developer to work within our cross-functional Agile team. You’ll be involved in full-cycle development and must be comfortable with frequent releases and iterations.",
		jobSkills: ["Agile", "Java", "Scrum"],
		employer: "Salesforce",
	},
	{
		title: "Cybersecurity Tools Engineer",
		text: "Our security team is looking for a developer to build tools for threat detection and response. Proficiency in Python, Linux scripting, and cloud security practices is necessary.",
		jobSkills: ["Cybersecurity", "Python", "Linux", "Bash", "AWS"],
		employer: "Cisco",
	},
];

export const cvURLS = [
	"https://firebasestorage.googleapis.com/v0/b/auth1-5688a.firebasestorage.app/o/userCV.pdf?alt=media&token=ac39d6e6-ff88-4e77-bf82-61c640387f05",
];

export const profilePicURLS = [
	"https://firebasestorage.googleapis.com/v0/b/auth1-5688a.firebasestorage.app/o/userPic1.jpeg?alt=media&token=a2e5b612-e08e-4ffb-acfc-96d3db4dd73e",
	"https://firebasestorage.googleapis.com/v0/b/auth1-5688a.firebasestorage.app/o/userPic2.jpeg?alt=media&token=6eb830d0-c261-419b-9492-c3d8132333cc",
];
